### PR TITLE
Fix: ES6 conversion and JSX use added (fixes #24)

### LINKED ISSUE #24: ES6 Conversion needed
### Subject of the issue
As titled.

### PR DESCRIPTION
**Pull request by zubairslamdien**
Fixes #24 

### Fix
* Now uses ES6 module syntax
* JSX template added

### CODE REVIEW

File: templates/hint.jsx [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+  } = props;
+
+  return (
+    <div className={classes(["hint__inner"])}>
+
+    <button className={classes([
+              'hint__btn',
+              'js-hint-btn-popup',
+              (_hint._button._iconClass) && 'btn-icon',
+              (_hint._button.alignIconRight) && 'align-icon-right',
```
Comment (kirsty-hames) [inline templates/hint.jsx]: Missing underscore for `_alignIconRight`

**Review by kirsty-hames — COMMENTED** [review]
This is working as expected thanks @zubairslamdien minus the `_alignIconRight` property I've raised separately.

The files could do with a tidy up, indentation and spacing wise. Adapt is typically indented with two spaces. Otherwise looking good to me.

File: js/HintView.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
+import Adapt from 'core/js/adapt';
+import React from 'react';
+import ReactDOM from 'react-dom';
+import { templates } from 'core/js/reactHelpers';
+import notify from 'core/js/notify';
+
+export default class HintView extends Backbone.View {
+
+    className() {
```
Comment (oliverfoster) [inline js/HintView.js]: 4 space indent should be two space

File: templates/hint.jsx [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+  const {
+    _globals,
+    _hint
+  } = props;
+
+  return (
+    <div className={classes(["hint__inner"])}>
+
+    <button className={classes([
+              'hint__btn',
```
Comment (oliverfoster) [inline templates/hint.jsx]: Very bad indenting.

File: templates/hint.jsx [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+        "hint__btn-text-inner"
+      ])}>
+      {_hint._button.text}
+      </span>
+    </span>
+    }
+
+  </button>
+
+</div>
```
Comment (oliverfoster) [inline templates/hint.jsx]: Pairs should have matching indent, line 11.

File: js/adapt-hint.js [hunk 5]
```diff
@@ -1,57 +1,19 @@
...
-      Adapt.notify.popup({
-        ...this.model.get('_hint'),
-        _classes: 'hint-popup'
-      });
-    }
-
-  });
-
-  Adapt.on('componentView:postRender', function (view) {
+  initHint(view) {
```
Comment (oliverfoster) [inline js/adapt-hint.js]:
```suggestion
  onComponentPostRender(view) {
```
Name tells us about the lifecycle without having to refer to the midpoint of line 6

File: templates/hint.jsx [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+import { classes } from 'core/js/reactHelpers';
+
+export default function Hint (props) {
+  const {
+    _globals,
+    _hint
+  } = props;
+
+  return (
+    <div className={classes(["hint__inner"])}>
```
Comment (oliverfoster) [inline templates/hint.jsx]:
```suggestion
    <div className="hint__inner">
```
`classes` function is for flattening, filtering and joining multiple classes arrays where some classes are falsey due to boolean flags. It lives here: https://github.com/adaptlearning/adapt-contrib-core/blob/de6fcd9c58ad7ed0d793920b048fcb213bdcc980/js/reactHelpers.js#L95-L101

File: templates/hint.jsx [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+            ])}
+            aria-label={classes([
+              (_hint._button.ariaLabel) ? _hint._button.ariaLabel : _globals._extensions._hint.openButtonText
+            ])}
+    >
+    
+    {_hint._button._iconClass &&
+      <span className={classes([
+        "hint__btn-icon"
+      ])}>
```
Comment (oliverfoster) [inline templates/hint.jsx]: single class, no need for `classes` function, please remove excessive use of classes function throughout

File: templates/hint.jsx [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+    <button className={classes([
+              'hint__btn',
+              'js-hint-btn-popup',
+              (_hint._button._iconClass) && 'btn-icon',
+              (_hint._button.alignIconRight) && 'align-icon-right',
+              (_hint._button.text) && 'btn-text'
+            ])}
+            aria-label={classes([
+              (_hint._button.ariaLabel) ? _hint._button.ariaLabel : _globals._extensions._hint.openButtonText
+            ])}
```
Comment (oliverfoster) [inline templates/hint.jsx]: classes function is not needed here.
```suggestion
            aria-label={_hint._button.ariaLabel ? _hint._button.ariaLabel : _globals._extensions._hint.openButtonText}
```
You also probably want to make a variable at the top of the template called "buttonAriaLabel":
```js
  const buttonAriaLabel = _hint._button.ariaLabel 
    ? _hint._button.ariaLabel 
    : _globals._extensions._hint.openButtonText;
```
Then
```suggestion
            aria-label={buttonAriaLabel}
```

File: templates/hint.jsx [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+    }
+
+    {_hint._button.text &&
+    <span className={classes([
+      "hint__btn-text"
+    ])}>
+      <span className={classes([
+        "hint__btn-text-inner"
+      ])}>
+      {_hint._button.text}
```
Comment (oliverfoster) [inline templates/hint.jsx]: compile function needed here

File: js/HintView.js [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+
+        const containsHeader = displayTitle || body || instruction;
+        const componentHeaderInner = $('.' + this.model.get('_id')).find('.component__header-inner');
+        const componentWidget = $('.' + this.model.get('_id')).find('.component__widget');
+        const targetSelector = containsHeader ? componentHeaderInner  : componentWidget;        
+
+        let hintElement = document.createElement("div");
+        hintElement.classList.add(this.className());
+
+        ReactDOM.render(<templates.hint {...data} />, hintElement);
```
Comment (oliverfoster) [inline js/HintView.js]:
```suggestion
        ReactDOM.render(<templates.hint {...data} />, this.el);
```
The element of this view already has the correct class and the element isn't in the dom elsewhere. There's no need to make another element.

File: js/HintView.js [hunk 11]
```diff
@@ -0,0 +1,57 @@
...
+
+export default class HintView extends Backbone.View {
+
+    className() {
+        return 'hint';
+    }
+
+    initialize() {
+        this.onHintPopupClicked = this.onHintPopupClicked.bind(this);
+
```
Comment (oliverfoster) [inline js/HintView.js]:
```suggestion
       this.$parentEl = $(`[data-adapt-id=${this.model.get('_id')]`)
```

Then reuse `this.$parentEl` throughout. The jQuery selector function `$()` has to search through the dom every time you lookup a selector to find all of the matching elements.

Please use [`data-adapt-id`](https://github.com/adaptlearning/adapt-contrib-core/blob/de6fcd9c58ad7ed0d793920b048fcb213bdcc980/js/views/adaptView.js#L15) instead of the class.

File: js/HintView.js [hunk 12]
```diff
@@ -0,0 +1,57 @@
...
+        
+        //Check if the component has a header to determine where the hint element will be created
+        const displayTitle = this.model.get('displayTitle');
+        const body = this.model.get('body');
+        const instruction = this.model.get('instruction');
+
+        const containsHeader = displayTitle || body || instruction;
+        const componentHeaderInner = $('.' + this.model.get('_id')).find('.component__header-inner');
+        const componentWidget = $('.' + this.model.get('_id')).find('.component__widget');
+        const targetSelector = containsHeader ? componentHeaderInner  : componentWidget;
```
Comment (oliverfoster) [inline js/HintView.js]: The is not a selector, it's a jQuery object with the found elements in it. 
```suggestion
        const $target = containsHeader ? componentHeaderInner  : componentWidget;        
```

File: js/adapt-hint.js [hunk 13]
```diff
@@ -1,57 +1,19 @@
...
     const hint = view.model.get('_hint');
     if (!hint || !hint._isEnabled) return;
```
Comment (oliverfoster) [inline js/adapt-hint.js]:
```suggestion
    if (!hint?._isEnabled) return;
```

**Review by oliverfoster — CHANGES_REQUESTED** [review]

**Comment by oliverfoster** [comment]
The logic looks mostly great. A few changes needed in names, variable placements, function misuse, variable content, lifecycle stuff with elements and view and the indentation. :+1:

**Comment by oliverfoster** [comment]
Could you implement the suggestions please? @zubairslamdien

**Comment by oliverfoster** [comment]
Ready for review

**Comment by zubairslamdien** [comment]
Tested and works great. @oliverfoster
