### PR TITLE
Fix: update a11y helpers (fixes #9)

### LINKED ISSUE #9: Popup doesn't support a11y_alt_text helper
As per https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/273

### Subject of the issue
The [a11y_alt_text](https://github.com/adaptlearning/adapt-contrib-core/commit/a92c7ffdb431bdf126e080c009b3b9c324642755) helper tag is getting displayed instead of compiling the on screen text and hidden screen reader text.

### Expected behaviour
Using the helper should produce display text with an alternative screen reader version.

### PR DESCRIPTION
**Pull request by kirsty-hames**
Fixes https://github.com/cgkineo/adapt-hint/issues/9

- replace deprecated `a11y_text`
- support [a11y_alt_text](https://github.com/adaptlearning/adapt-contrib-core/commit/a92c7ffdb431bdf126e080c009b3b9c324642755) helper.

## PR Test
Apply the following config to any component.
```
        "_hint": {
            "_items": [
                {
                    "title": "Adapt Hint {{a11y_alt_text '$5bn' 'five billion dollars'}}",
                    "body": "An extension {{a11y_alt_text '$5bn' 'five billion dollars'}} that adds a small, clickable icon to a component that displays additional information."
                },
                {
                    "title": "Additional",
                    "body": "Information"
                }
            ],
            "_isNotifyPopup": true
        }
```
In your course, select the hint button to trigger the popup. The `a11y_alt_text` helper syntax shouldn't be visible within the popup display text and instead should just display '$5bn'. 

Using the browser devtools, inspect '$5bn' and the helper should have split out the on screen text and a11y text e.g.
`<span aria-hidden="true">$5bn</span><span class="aria-label">five billion dollars</span>`

Please test with `"_isNotifyPopup": false` also.

### CODE REVIEW

File: js/adapt-hint.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 define([
-  'core/js/adapt'
-], function (Adapt) {
+  'core/js/adapt',
+  'core/js/reactHelpers'
```
Comment (oliverfoster) [inline js/adapt-hint.js]: You shouldn't need to import this here unless you're calling it in this js file. `compile` is also a handlebars helper, two functions, same name, same behaviour, different use-cases. This one is to compile handlebars in jsx files, the handlebars helper is to compile handlebars in a handlebars template.

**Comment by kirsty-hames** [comment]
Thanks @oliverfoster. I accidentally hit 'resolve' thinking it would give me options to amend the file. Would you mind reviewing again please?

**Review by StuartNicholls — APPROVED** [review]

**Comment by swashbuck** [comment]
@kirsty-hames Did you want to compile the `title` as well as the `body`? Also, do you have a test case I can use?

**Comment by kirsty-hames** [comment]
> @kirsty-hames Did you want to compile the `title` as well as the `body`? Also, do you have a test case I can use?

Good spot, thanks @swashbuck. Titles updated in commit https://github.com/cgkineo/adapt-hint/pull/10/commits/f9d179c4ffc8711de9f3c02c1572dba748a19dff and  https://github.com/cgkineo/adapt-hint/pull/10/commits/f9d179c4ffc8711de9f3c02c1572dba748a19dff. Test case added above.

**Review by swashbuck — APPROVED** [review]
👍
